version: '3'

services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: supermarket-image
    container_name: supermarket-api
    ports:
      - "3333:3333"
    networks:
      - supermarket-network
    volumes:
      - .:/usr/src/api
    working_dir: "/usr/src/api"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    container_name: supermarket-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supermarket
      - POSTGRES_USER=supermarket
      - POSTGRES_PASSWORD=superpass
    networks:
      - supermarket-network
  redis:
    image: redis
    container_name: supermarket-redis
    command: redis-server --requirepass redis-events
    ports:
      - "6379:6379"
    networks:
      - supermarket-network

networks:
  supermarket-network:
    driver: bridge
